# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Iris.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Iris.proto',
  package='h2o',
  syntax='proto3',
  serialized_options=_b('\n\026tech.thomaslegrand.h2oB\tIrisProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\nIris.proto\x12\x03h2o\"_\n\x0bIrisRequest\x12\x13\n\x0bSepalLength\x18\x01 \x01(\x01\x12\x12\n\nSepalWidth\x18\x02 \x01(\x01\x12\x13\n\x0bPetalLength\x18\x03 \x01(\x01\x12\x12\n\nPetalWidth\x18\x04 \x01(\x01\"\x1c\n\tIrisReply\x12\x0f\n\x07species\x18\x01 \x01(\t2:\n\tPredictor\x12-\n\x07Predict\x12\x10.h2o.IrisRequest\x1a\x0e.h2o.IrisReply\"\x00\x42+\n\x16tech.thomaslegrand.h2oB\tIrisProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_IRISREQUEST = _descriptor.Descriptor(
  name='IrisRequest',
  full_name='h2o.IrisRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SepalLength', full_name='h2o.IrisRequest.SepalLength', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='SepalWidth', full_name='h2o.IrisRequest.SepalWidth', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PetalLength', full_name='h2o.IrisRequest.PetalLength', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PetalWidth', full_name='h2o.IrisRequest.PetalWidth', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=114,
)


_IRISREPLY = _descriptor.Descriptor(
  name='IrisReply',
  full_name='h2o.IrisReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='species', full_name='h2o.IrisReply.species', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=144,
)

DESCRIPTOR.message_types_by_name['IrisRequest'] = _IRISREQUEST
DESCRIPTOR.message_types_by_name['IrisReply'] = _IRISREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IrisRequest = _reflection.GeneratedProtocolMessageType('IrisRequest', (_message.Message,), dict(
  DESCRIPTOR = _IRISREQUEST,
  __module__ = 'Iris_pb2'
  # @@protoc_insertion_point(class_scope:h2o.IrisRequest)
  ))
_sym_db.RegisterMessage(IrisRequest)

IrisReply = _reflection.GeneratedProtocolMessageType('IrisReply', (_message.Message,), dict(
  DESCRIPTOR = _IRISREPLY,
  __module__ = 'Iris_pb2'
  # @@protoc_insertion_point(class_scope:h2o.IrisReply)
  ))
_sym_db.RegisterMessage(IrisReply)


DESCRIPTOR._options = None

_PREDICTOR = _descriptor.ServiceDescriptor(
  name='Predictor',
  full_name='h2o.Predictor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=204,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='h2o.Predictor.Predict',
    index=0,
    containing_service=None,
    input_type=_IRISREQUEST,
    output_type=_IRISREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTOR)

DESCRIPTOR.services_by_name['Predictor'] = _PREDICTOR

# @@protoc_insertion_point(module_scope)
